import type { ResolvedTarget } from '../../targets/targets.js';

/**
 * The overlay layered on top of Signals-DPG/local-setup/docker-compose.yml.
 *
 * That file is the authoritative local stack and already carries postgres,
 * redis, stock Keycloak with its mounts, the user-profile fixup, mailpit, the
 * bootstrap tools one-shot, signals-api, TEI and signals-search api+worker.
 * The harness changes only what a verification run needs and inherits
 * everything else, including the reasoning in its comments.
 */
export function renderOverlay(opts: {
  target: ResolvedTarget;
  digests: Record<string, string>;
  timing: Record<string, string>;
}): string {
  const { target, digests, timing } = opts;
  const networkMount = `${target.networkConfigPath}:/networks/network.json:ro`;

  const searchEnv = [
    `      NETWORK_CONFIG_PATH: /networks/network.json`,
    `      SWEEP_INTERVAL_MS: "${timing.SWEEP_INTERVAL_MS}"`,
    `      CACHE_TTL_SECONDS: "${timing.CACHE_TTL_SECONDS}"`,
    `      PEL_MIN_IDLE_MS: "${timing.PEL_MIN_IDLE_MS}"`,
  ].join('\n');

  return `# GENERATED by bluedots-e2e — do not edit.
# Overlay on Signals-DPG/local-setup/docker-compose.yml for target ${target.id}.
services:
  signals-bootstrap:
    image: signals-dpg-journey/bootstrap:local
    environment:
      NETWORK_CONFIG_SOURCE: local
      NETWORK_CONFIG_LOCAL_FILE: /networks/network.json
    volumes:
      - ${networkMount}

  signals-api:
    image: ghcr.io/blue-dots-economy/signals-dpg/api@${digests['signals-dpg']}
    build: !reset null
    environment:
      NETWORK_CONFIG_SOURCE: local
      NETWORK_CONFIG_LOCAL_FILE: /networks/network.json
    volumes:
      - ${networkMount}

  # Not needed: journeys assert over HTTP. Moving it behind an unused profile
  # keeps it defined without booting it.
  signals-ui:
    profiles: ["ui"]

  signals-search-api:
    image: ghcr.io/blue-dots-economy/signals-search@${digests['signals-search']}
    environment:
${searchEnv}
    volumes:
      - ${networkMount}

  signals-search-worker:
    image: ghcr.io/blue-dots-economy/signals-search@${digests['signals-search']}
    environment:
${searchEnv}
    volumes:
      - ${networkMount}
`;
}
