import { stat } from 'node:fs/promises';
import type { ResolvedTarget } from '../../targets/target_discovery.js';
import {
  AGGREGATOR_API_PORT,
  AGGREGATOR_DB,
  KEYCLOAK_ISSUER,
  NOTIFICATION_PORT,
  SIGNALS_ACTING_ORG_ID,
  SIGNALS_ACTING_ORG_SLUG,
  MINIO_PORT,
} from './stack_env.js';
import { resetFor } from './base_services.js';

/**
 * The overlay layered on top of Signals-DPG/local-setup/docker-compose.yml.
 *
 * NOTE: the YAML below lives inside a template literal, so a backtick in a
 * comment opens a nested expression and breaks the parse with a message
 * that points at the wrong token. Write command names bare.
 *
 * That file is the authoritative local stack and already carries postgres,
 * redis, stock Keycloak with its mounts, the user-profile fixup, mailpit, the
 * bootstrap tools one-shot, signals-api, TEI and signals-search api+worker.
 * The harness changes only what a verification run needs and inherits
 * everything else, including the reasoning in its comments.
 */
export function renderOverlay(opts: {
  target: ResolvedTarget;
  digests: Record<string, string>;
  timing: Record<string, string>;
  /** Absolute path to the aggregator-dpg checkout (render script + themes). */
  aggregatorRoot?: string;
  /** Directory holding the prepared realm export (see prepareRealm). */
  realmDir?: string;
  /** Directory holding the stub embedder source, when embedder is 'stub'. */
  stubDir?: string;
  /** Directory holding the generated internal-secrets.json. */
  notificationSecretsDir?: string;
  /**
   * Extra env for the search services. Exists for the negative controls,
   * which need to break ingestion deliberately -- e.g. pointing the worker
   * at a decoy consumer group so the sweep is the only path left.
   */
  searchOverrides?: Record<string, string>;
  /**
   * `tei` (default) runs the real embedder, whose vectors are the ones
   * production computes. `stub` swaps in a deterministic stand-in that
   * removes a multi-GB pull and a CPU-bound warmup, at the cost of ranking
   * quality corresponding to nothing deployed.
   */
  embedder?: 'tei' | 'stub';
}): string {
  const { target, digests, timing, aggregatorRoot, realmDir, notificationSecretsDir } = opts;

  // Mount the target DIRECTORY, not the single network.json.
  // loadConsentConfigs reads consent.json from dirname(NETWORK_CONFIG_LOCAL_FILE),
  // and without it resolveConsentVersion returns null, consent is skipped
  // silently ("category not configured -- do not fail onboarding"), and the
  // profile stays draft: invisible to search, with a 200 on the way in.
  const targetDir = target.networkConfigPath.replace(/\/[^/]+$/, '');
  const networkMount = `${targetDir}:/networks:ro`;

  // Merged, not appended: an override repeating a timing key would emit
  // the key twice and strict YAML rejects duplicate mapping keys with an
  // unhelpful "construct errors".
  const searchEnvEntries: Record<string, string> = {
    NETWORK_CONFIG_PATH: '/networks/network.json',
    SWEEP_INTERVAL_MS: timing.SWEEP_INTERVAL_MS!,
    CACHE_TTL_SECONDS: timing.CACHE_TTL_SECONDS!,
    PEL_MIN_IDLE_MS: timing.PEL_MIN_IDLE_MS!,
    ...(opts.searchOverrides ?? {}),
  };
  const searchEnv = Object.entries(searchEnvEntries)
    .map(([k, v]) => `      ${k}: "${v}"`)
    .join('\n');

  // Name reset and port made ephemeral, both from BASE_SERVICES. The base
  // compose is built for a developer running ONE stack: it names every
  // container and binds fixed host ports. A harness has to coexist with
  // whatever that developer already has up, and with a run for another
  // target. See base_services.ts for why this is a table and not a stanza
  // written out per service.
  const reset = resetFor;

  return `# GENERATED by bluedots-e2e — do not edit.
# Overlay on Signals-DPG/local-setup/docker-compose.yml for target ${target.id}.
services:
  postgres:
${reset('postgres')}

  redis:
${reset('redis')}

  keycloak:
${reset('keycloak')}
    # ONE environment key for this service. The aggregator branch below
    # appends to this block rather than opening a second one: compose reads
    # a duplicate mapping key as a YAML error, not as a merge.
    environment:
      # Pins the issuer. The host port is ephemeral, and with
      # KC_HOSTNAME_STRICT false keycloak derives iss from the request URL,
      # so a token taken through that port carries it in iss -- while
      # signals-api compares iss byte-for-byte against KEYCLOAK_BASE_URL,
      # which is fixed. Every such token 401s on first use.
      KC_HOSTNAME: ${KEYCLOAK_ISSUER}${
    aggregatorRoot
      ? `
    # aggregator-dpg's realm export is the only one carrying all eight
    # clients a four-service stack needs, and it must be rendered by
    # aggregator's OWN script: signals' substitutes 11 placeholders where
    # aggregator's substitutes 19, and signals' substitutes neither the realm
    # name nor any client secret. Rendering this export through signals'
    # script imports a realm literally named __KEYCLOAK_REALM__ whose clients
    # have __*_SECRET__ for secrets.
    #
    # The themes mount is replaced rather than added: signals-ui in this
    # realm sets login_theme: signals, which exists only under
    # aggregator-dpg, and aggregator's themes dir also carries otp, so it is
    # a superset.
    # !override, not a plain volumes key: compose APPENDS sequences, so
    # otherwise signals' themes and aggregator's themes both target
    # /opt/keycloak/themes and the mounts collide. Overriding drops
    # everything the base declared, so the provider jar and the named data
    # volume are restated here.
    # aggregator's render script substitutes 19 placeholders where signals'
    # substitutes 11, so it needs variables the base compose never passes to
    # this container. An .env file only feeds compose-file interpolation --
    # it does not reach the container -- so they are declared here, under
    # the environment key opened above.
      KEYCLOAK_REALM: \${KEYCLOAK_REALM}
      AGGREGATOR_API_SECRET: \${AGGREGATOR_API_SECRET}
      AGGREGATOR_PORTAL_SECRET: \${AGGREGATOR_PORTAL_SECRET}
      AGGREGATOR_BFF_SECRET: \${AGGREGATOR_BFF_SECRET}
      SIGNALS_API_SECRET: \${SIGNALS_API_SECRET}
      CAMPAIGN_MANAGER_SECRET: \${CAMPAIGN_MANAGER_SECRET}
      VOICE_DPG_SIGNALS_SECRET: \${VOICE_DPG_SIGNALS_SECRET}
      SIGNALSTACK_CLIENT_SECRET: \${SIGNALSTACK_CLIENT_SECRET}
    volumes: !override
      - ${aggregatorRoot}/infra/keycloak/render-realm.sh:/opt/keycloak/render-realm.sh:ro
      - ${realmDir ?? `${aggregatorRoot}/infra/keycloak/realms`}:/opt/keycloak/data/import-template:ro
      - ${aggregatorRoot}/infra/keycloak/providers:/opt/keycloak/providers:ro
      - ${aggregatorRoot}/infra/keycloak/themes:/opt/keycloak/themes:ro
      - signals-keycloak-data:/opt/keycloak/data`
      : ''
  }

  # NOT in the base compose -- signals-dpg's local-setup does not run it,
  # which is why getNotificationClient() returned undefined and the whole
  # notification pipeline was unassertable rather than merely untested.
  # Defined here in full rather than overridden.
  #
  # No published port: signals-api reaches it over the compose network, and
  # the harness asserts on the Redis queue it writes to rather than on HTTP.
  # Delivery itself needs SES or Gmail credentials, so a hermetic run can
  # verify the hop and the queued job, never the inbox.
  notification-service:
    image: ghcr.io/blue-dots-economy/notification-service@${digests['notification-service']}
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    environment:
      SERVER_PORT: "${NOTIFICATION_PORT}"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_PASSWORD: \${REDIS_PASSWORD}
      INTERNAL_SECRETS_JSON: /app/config/internal-secrets.json
      # Logs the recipient of every send. The worker has no transport
      # configured, so a job fails after this line -- the log is the only
      # place the intended recipient appears.
      MAIL_LOG: "true"
    volumes:
      - ${notificationSecretsDir ?? '/tmp'}:/app/config:ro
    healthcheck:
      # /openapi.json is the only unauthenticated route; everything else is
      # behind the HMAC preHandler and would answer 401 forever.
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:${NOTIFICATION_PORT}/openapi.json').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 5s
      timeout: 3s
      retries: 20

${
    aggregatorRoot
      ? `  # Creates aggregator-dpg's database. Its API migrates itself on boot
  # but will not CREATE the database, and signals-dpg's base compose ships
  # \`postgresdb\` with no init directory -- aggregator's OWN compose makes
  # this the default database, so nothing in the stack this harness boots
  # makes it. A one-shot rather than an init script: the base's postgres
  # volume survives a re-run, and an initdb.d script only ever runs on an
  # empty data directory.
  aggregator-db-init:
    image: postgres:17-alpine
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: \${POSTGRES_PASSWORD}
    # Idempotent: a second run finds the row and skips. Quoted -c body so the
    # inner quoting survives both YAML and sh.
    command:
      - sh
      - -c
      - >-
        psql -h postgres -U \${POSTGRES_USER:-postgres} -d postgresdb -tc
        "SELECT 1 FROM pg_database WHERE datname = '${AGGREGATOR_DB}'"
        | grep -q 1 ||
        psql -h postgres -U \${POSTGRES_USER:-postgres} -d postgresdb -c
        "CREATE DATABASE ${AGGREGATOR_DB}"

  # Object storage for bulk uploads. No published host port: every
  # presigned URL is signed over its Host header, so the URL cannot be
  # re-based onto a discovered port the way an emailed link can, and
  # publishing a fixed one is the collision this overlay exists to avoid.
  # The upload is issued from inside the network instead.
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    restart: unless-stopped
    command: ["server", "/data"]
    environment:
      MINIO_ROOT_USER: \${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: \${MINIO_ROOT_PASSWORD}
      MINIO_REGION: \${S3_REGION}
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:${MINIO_PORT}/minio/health/live || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

  # The bucket, once. Idempotent, so a re-run against a surviving volume is
  # a no-op rather than an error.
  minio-init:
    image: minio/mc:RELEASE.2025-04-16T18-13-26Z
    restart: "no"
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: \${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: \${MINIO_ROOT_PASSWORD}
      S3_BUCKET: \${S3_BUCKET}
    entrypoint:
      - sh
      - -c
      - |
        set -e
        mc alias set local http://minio:${MINIO_PORT} "$$MINIO_ROOT_USER" "$$MINIO_ROOT_PASSWORD"
        mc mb --ignore-existing "local/$$S3_BUCKET"

  # The signals organisation the aggregator acts as, created with a KNOWN
  # id. aggregator-api reads that id from its environment at boot, and the
  # row can only exist once signals' schema does -- the same ordering
  # problem the search caller key has.
  #
  # Idempotent on the unique slug, and shaped exactly as signals' own
  # seeding shapes it: that script looks the row up BY slug and returns it
  # untouched when present, so this makes the id knowable without producing
  # anything the product would not have produced itself.
  #
  # type matters as much as the id. resolveServiceAccount admits only a
  # service org type, so a row without one authenticates nobody.
  signals-org-init:
    image: postgres:17-alpine
    restart: "no"
    depends_on:
      signals-bootstrap:
        condition: service_completed_successfully
    environment:
      PGPASSWORD: \${POSTGRES_PASSWORD}
    command:
      - sh
      - -c
      - >-
        psql -h postgres -U \${POSTGRES_USER:-postgres} -d postgresdb -v ON_ERROR_STOP=1 -c
        "INSERT INTO organization (id, slug, name, type, created_at)
         VALUES ('${SIGNALS_ACTING_ORG_ID}', '${SIGNALS_ACTING_ORG_SLUG}',
                 '${SIGNALS_ACTING_ORG_SLUG}', 'network_service', now())
         ON CONFLICT (slug) DO NOTHING"

  # NOT in the base compose -- signals-dpg's local-setup runs signals only.
  # Defined here in full, like notification-service above.
  #
  # No published host port. The approval emails carry links built from
  # PUBLIC_API_URL, and a journey re-bases those onto the discovered
  # ephemeral port rather than trusting the host in the mail: the host is a
  # deployment setting, the path and the token are the behaviour.
  aggregator-api:
    image: ghcr.io/blue-dots-economy/aggregator-dpg/api@${digests['aggregator-dpg']}
    restart: unless-stopped
    ports:
      - "0:${AGGREGATOR_API_PORT}"
    depends_on:
      aggregator-db-init:
        condition: service_completed_successfully
      # For the acting org row, not for the schema: an approval that cannot
      # name an organisation aborts.
      signals-org-init:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      # The realm must carry unmanagedAttributePolicy=ENABLED before the API
      # creates any user, or the aggregator_id / decision_made attributes are
      # dropped on the floor -- and every later token is missing the claims
      # the approval gate reads.
      keycloak-init:
        condition: service_completed_successfully
    environment:
      NODE_ENV: production
      PORT: "${AGGREGATOR_API_PORT}"
      HOST: "0.0.0.0"
      DATABASE_URL: postgres://\${POSTGRES_USER:-postgres}:\${POSTGRES_PASSWORD}@postgres:5432/${AGGREGATOR_DB}
      RUN_MIGRATIONS_ON_BOOT: "true"
      # Shares signals' Redis rather than running a second one. BullMQ keys
      # are \`bull:*\`; the ingest stream and the notification dedupe keys this
      # suite reads are neither, so the two cannot collide.
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis:6379
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: \${KEYCLOAK_REALM}
      KEYCLOAK_ADMIN_CLIENT_ID: aggregator-api
      KEYCLOAK_ADMIN_CLIENT_SECRET: \${AGGREGATOR_API_SECRET}
      KEYCLOAK_ALLOWED_AZP: \${KEYCLOAK_ALLOWED_AZP}
      ORG_HIERARCHY_ENABLED: \${ORG_HIERARCHY_ENABLED}
      MAIL_PROVIDER: smtp
      SMTP_HOST: mailpit
      SMTP_PORT: "1025"
      SMTP_SECURE: "false"
      SMTP_FROM: no-reply@journey.test
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      APPROVAL_TOKEN_SECRET: \${APPROVAL_TOKEN_SECRET}
      ADMIN_EMAILS: \${ADMIN_EMAILS}
      PUBLIC_API_URL: http://localhost:${AGGREGATOR_API_PORT}
      PUBLIC_PORTAL_URL: http://localhost:3100
      PUBLIC_LINK_BASE_URL: http://localhost:3100
      SCHEMA_ROOT_DIR: /app/config/\${AGGREGATOR_NETWORK}/schemas
      AGGREGATOR_CONFIG_PATH: /app/config/\${AGGREGATOR_NETWORK}/aggregator.config.yaml
      # Keycloak, not the retiring api-key path. The client id doubles as the
      # signals organisation slug -- that is how resolveServiceAccount finds
      # the org -- and signals refuses the token outright unless the same id
      # is in its KEYCLOAK_SERVICE_CLIENT_IDS.
      SIGNALSTACK_AUTH_MODE: \${SIGNALSTACK_AUTH_MODE}
      SIGNALSTACK_BASE_URL: \${SIGNALSTACK_BASE_URL}
      SIGNALSTACK_CLIENT_ID: \${SIGNALSTACK_CLIENT_ID}
      SIGNALSTACK_CLIENT_SECRET: \${SIGNALSTACK_CLIENT_SECRET}
      SIGNALSTACK_ACTING_ORG_ID: \${SIGNALSTACK_ACTING_ORG_ID}
      SIGNALSTACK_ITEM_NETWORK: \${AGGREGATOR_NETWORK}
      # Both endpoints the compose name. The public one is what gets signed
      # into every presigned URL, and SigV4 covers the Host header -- so it
      # has to be somewhere the signature stays valid AND something inside
      # the network can reach.
      S3_REGION: \${S3_REGION}
      S3_BUCKET: \${S3_BUCKET}
      S3_FORCE_PATH_STYLE: "true"
      S3_ENDPOINT: http://minio:${MINIO_PORT}
      S3_PUBLIC_ENDPOINT: http://minio:${MINIO_PORT}
      S3_ACCESS_KEY_ID: \${MINIO_ROOT_USER}
      S3_SECRET_ACCESS_KEY: \${MINIO_ROOT_PASSWORD}
    volumes:
      - ${aggregatorRoot}/config:/app/config:ro
    healthcheck:
      # CMD with node, never CMD-SHELL: the image is a hardened base with no
      # /bin/sh, so a shell probe can never pass and the container sits
      # unhealthy forever -- which blocks everything waiting on it.
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:${AGGREGATOR_API_PORT}/health/ready').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 15s

`
      : ''
  }  # One block on every path. The fixed name tei-embeddings is global to
  # the docker daemon, so the default (real TEI) path -- the one CI takes
  # -- collided with any other stack running an embedder. The stub adds
  # keys here rather than declaring the service a second time: a duplicate
  # mapping key is not a merge, it is the last one winning.
  tei-embeddings:
${reset('tei-embeddings')}
${
    opts.embedder === 'stub'
      ? `    # Overridden in place, keeping the service name: EMBEDDING_BASE_URL
    # points at http://tei-embeddings:80/v1, so nothing downstream needs to
    # know which embedder is running. Runs from the signals-search image,
    # which this stack already pulls, so choosing the stub adds no image.
    image: ghcr.io/blue-dots-economy/signals-search@${digests['signals-search']}
    platform: !reset null
    entrypoint: !override ["node"]
    command: !override ["/stub/stub_embedder.js"]
    environment:
      EMBEDDING_DIM: "1024"
    volumes: !override
      - ${opts.stubDir ?? '/stub'}:/stub:ro
`
      : ''
  }  # Runs under the keycloak profile, which every run enables, and seeding
  # waits on it. Nothing reset its name before.
  keycloak-init:
${reset('keycloak-init')}

  mailpit:
${reset('mailpit')}
    # The base healthcheck uses /dev/tcp/127.0.0.1/8025, a bash builtin. The
    # mailpit image ships sh and no bash, so CMD-SHELL can never satisfy it
    # and the container sits permanently unhealthy -- invisible until
    # something waits on health, which up --wait does. wget is present in
    # the image and answers the same question.
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8025/readyz || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  # Built from local-setup/infra/signals-bootstrap.Dockerfile by the base
  # compose. Naming an image here would make compose try to pull it first.
  signals-bootstrap:
${reset('signals-bootstrap')}
    environment:
      NETWORK_CONFIG_SOURCE: local
      NETWORK_CONFIG_LOCAL_FILE: /networks/network.json
    volumes: !override
      - ${networkMount}

  signals-api:
    image: ghcr.io/blue-dots-economy/signals-dpg/api@${digests['signals-dpg']}
    build: !reset null
${reset('signals-api')}
    # The image ships --interval=30s --start-period=10s --retries=3. Booting
    # alongside Keycloak and an emulated TEI, the API misses that start
    # period and the 30s interval then makes recovery slow enough for
    # up --wait to give up on a service that is merely slow. Poll more
    # often over a longer window: converges quickly, hides nothing.
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:2742/health/live').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 3s
      timeout: 3s
      start_period: 120s
      retries: 40
    environment:
      NETWORK_CONFIG_SOURCE: local
      NETWORK_CONFIG_LOCAL_FILE: /networks/network.json
      # Declared HERE, not merely in the .env file. An env_file feeds
      # compose-file interpolation; it does not reach the container. The
      # base compose passes neither of these groups to signals-api, so the
      # API ran with both unset and said so only in a level-40 log line:
      #
      #   "signals-search is not configured (SIGNALS_SEARCH_URL/
      #    SIGNALS_SEARCH_API_KEY unset)"
      #
      # The discover BFF falls back to a native distance/recency query when
      # that happens, so the browse-feed journeys passed while never
      # crossing into signals-search at all -- green, and proving less than
      # they claimed. Same shape as the KEYCLOAK_REALM bug this file
      # already carries a note about.
      SIGNALS_SEARCH_URL: http://signals-search-api:3100
      SIGNALS_SEARCH_API_KEY: \${SIGNALS_SEARCH_API_KEY}
      # And without all three of these getNotificationClient() returns
      # undefined, so the API sends nothing and logs nothing -- which is
      # exactly what the notification journeys saw.
      NOTIFICATION_SERVICE_ENDPOINT: \${NOTIFICATION_SERVICE_ENDPOINT}
      NOTIFICATION_SERVICE_KEY_ID: \${NOTIFICATION_SERVICE_KEY_ID}
      NOTIFICATION_SERVICE_SECRET: \${NOTIFICATION_SERVICE_SECRET}
      # Both required by resolveNotifierConfig, which returns null without
      # logging when either is missing -- the reason the first run with a
      # notification client still sent nothing at all.
      NOTIFICATION_FROM_EMAIL: \${NOTIFICATION_FROM_EMAIL}
      FRONTEND_BASE_URL: \${FRONTEND_BASE_URL}
    volumes: !override
      - ${networkMount}

  # Runs the bulk pipeline: file-process, then a job per row, then the
  # finalise that writes errors.csv. Nothing observes it directly -- the
  # journeys assert on what reaches signals -- but without it an upload
  # transitions to running and stays there forever, which reads as a slow
  # stack rather than an absent service.
  aggregator-worker:
    image: ghcr.io/blue-dots-economy/aggregator-dpg/worker@${digests['aggregator-dpg-worker']}
    restart: unless-stopped
    depends_on:
      aggregator-api:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://\${POSTGRES_USER:-postgres}:\${POSTGRES_PASSWORD}@postgres:5432/${AGGREGATOR_DB}
      REDIS_URL: redis://:\${REDIS_PASSWORD}@redis:6379
      S3_REGION: \${S3_REGION}
      S3_BUCKET: \${S3_BUCKET}
      S3_FORCE_PATH_STYLE: "true"
      S3_ENDPOINT: http://minio:${MINIO_PORT}
      S3_PUBLIC_ENDPOINT: http://minio:${MINIO_PORT}
      S3_ACCESS_KEY_ID: \${MINIO_ROOT_USER}
      S3_SECRET_ACCESS_KEY: \${MINIO_ROOT_PASSWORD}
      MAIL_PROVIDER: smtp
      SMTP_HOST: mailpit
      SMTP_PORT: "1025"
      SMTP_SECURE: "false"
      SMTP_FROM: no-reply@journey.test
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SCHEMA_ROOT_DIR: /app/config/\${AGGREGATOR_NETWORK}/schemas
      AGGREGATOR_CONFIG_PATH: /app/config/\${AGGREGATOR_NETWORK}/aggregator.config.yaml
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: \${KEYCLOAK_REALM}
      # The same Keycloak push the API uses, and the same trap: without the
      # acting org the writer answers SIGNALSTACK_CONFIG_MISSING and every
      # row is processed and sent nowhere. aggregator's own compose omits
      # this one from the worker too.
      SIGNALSTACK_AUTH_MODE: \${SIGNALSTACK_AUTH_MODE}
      SIGNALSTACK_BASE_URL: \${SIGNALSTACK_BASE_URL}
      SIGNALSTACK_CLIENT_ID: \${SIGNALSTACK_CLIENT_ID}
      SIGNALSTACK_CLIENT_SECRET: \${SIGNALSTACK_CLIENT_SECRET}
      SIGNALSTACK_ACTING_ORG_ID: \${SIGNALSTACK_ACTING_ORG_ID}
      SIGNALSTACK_ITEM_NETWORK: \${AGGREGATOR_NETWORK}
    volumes:
      - ${aggregatorRoot}/config:/app/config:ro

  # Not needed: journeys assert over HTTP. Moving it behind an unused profile
  # keeps it defined without booting it.
  signals-ui:
    profiles: ["ui"]

  signals-search-api:
    image: ghcr.io/blue-dots-economy/signals-search@${digests['signals-search']}
${reset('signals-search-api')}
    environment:
${searchEnv}
    volumes: !override
      - ${networkMount}

  signals-search-worker:
    image: ghcr.io/blue-dots-economy/signals-search@${digests['signals-search']}
${reset('signals-search-worker')}
    environment:
${searchEnv}
    volumes: !override
      - ${networkMount}
`;
}

/**
 * Fail before boot if a bind source is missing or is not a file.
 *
 * Docker creates a missing bind source as an empty DIRECTORY rather than
 * erroring, so the mistake surfaces much later as an EISDIR crash inside a
 * container, with nothing pointing back at the path that was wrong.
 */
/**
 * A mount source, and what it has to be.
 *
 * Four of the six the overlay mounts are directories -- the realm dir, the
 * providers dir, the themes dir and the stub dir. A checker that demanded a
 * file could not describe them, which is why only network.json was ever
 * passed to it.
 */
export type BindSource = string | { path: string; kind: 'file' | 'directory' };

export async function assertBindSources(sources: readonly BindSource[]): Promise<void> {
  for (const source of sources) {
    const { path, kind } = typeof source === 'string' ? { path: source, kind: 'file' as const } : source;

    let stats;
    try {
      stats = await stat(path);
    } catch {
      // Prefixed, because classifyFailure reads the prefix: without one, a
      // wrong AGGREGATOR_DPG_PATH -- the likeliest misconfiguration on a
      // fresh machine -- reported as a PRODUCT failure and would block the
      // release candidate over a path on somebody's laptop.
      throw new Error(
        `BIND_SOURCE_MISSING: ${path} does not exist. Docker would create it as an ` +
          `empty directory and the failure would surface much later, inside a container.`,
      );
    }

    const ok = kind === 'file' ? stats.isFile() : stats.isDirectory();
    if (!ok) {
      throw new Error(
        `BIND_SOURCE_WRONG_KIND: ${path} is not a ${kind}. Mounting it would ` +
          `${kind === 'file' ? 'shadow the file the container expects' : 'replace the directory with a single file'}.`,
      );
    }
  }
}
