import type { ResolvedTarget } from '../../targets/targets.js';

/**
 * The overlay layered on top of Signals-DPG/local-setup/docker-compose.yml.
 *
 * That file is the authoritative local stack and already carries postgres,
 * redis, stock Keycloak with its mounts, the user-profile fixup, mailpit, the
 * bootstrap tools one-shot, signals-api, TEI and signals-search api+worker.
 * The harness changes only what a verification run needs and inherits
 * everything else, including the reasoning in its comments.
 */
export function renderOverlay(opts: {
  target: ResolvedTarget;
  digests: Record<string, string>;
  timing: Record<string, string>;
}): string {
  const { target, digests, timing } = opts;
  const networkMount = `${target.networkConfigPath}:/networks/network.json:ro`;

  const searchEnv = [
    `      NETWORK_CONFIG_PATH: /networks/network.json`,
    `      SWEEP_INTERVAL_MS: "${timing.SWEEP_INTERVAL_MS}"`,
    `      CACHE_TTL_SECONDS: "${timing.CACHE_TTL_SECONDS}"`,
    `      PEL_MIN_IDLE_MS: "${timing.PEL_MIN_IDLE_MS}"`,
  ].join('\n');

  // The base compose publishes fixed host ports (5432, 5555, 8080, 8025,
  // 2742, 3100) because it is built for a developer running ONE stack. A
  // harness has to coexist with whatever that developer already has up, and
  // with a run for a different target, so every published port becomes
  // ephemeral and is discovered after boot.
  //
  // `!override` matters: compose MERGES sequences, so a plain `ports:` here
  // would append to the base list and keep the fixed bindings.
  const ephemeral = (containerPort: number) =>
    `    ports: !override\n      - "0:${containerPort}"`;

  return `# GENERATED by bluedots-e2e — do not edit.
# Overlay on Signals-DPG/local-setup/docker-compose.yml for target ${target.id}.
services:
  postgres:
${ephemeral(5432)}

  redis:
${ephemeral(6379)}

  keycloak:
${ephemeral(8080)}

  mailpit:
${ephemeral(8025)}

  # Built from local-setup/infra/signals-bootstrap.Dockerfile by the base
  # compose. Naming an image here would make compose try to pull it first.
  signals-bootstrap:
    environment:
      NETWORK_CONFIG_SOURCE: local
      NETWORK_CONFIG_LOCAL_FILE: /networks/network.json
    volumes:
      - ${networkMount}

  signals-api:
    image: ghcr.io/blue-dots-economy/signals-dpg/api@${digests['signals-dpg']}
    build: !reset null
${ephemeral(2742)}
    environment:
      NETWORK_CONFIG_SOURCE: local
      NETWORK_CONFIG_LOCAL_FILE: /networks/network.json
    volumes:
      - ${networkMount}

  # Not needed: journeys assert over HTTP. Moving it behind an unused profile
  # keeps it defined without booting it.
  signals-ui:
    profiles: ["ui"]

  signals-search-api:
    image: ghcr.io/blue-dots-economy/signals-search@${digests['signals-search']}
${ephemeral(3100)}
    environment:
${searchEnv}
    volumes:
      - ${networkMount}

  signals-search-worker:
    image: ghcr.io/blue-dots-economy/signals-search@${digests['signals-search']}
    environment:
${searchEnv}
    volumes:
      - ${networkMount}
`;
}
