/**
 * Regenerate the typed API clients from each service's committed OpenAPI
 * spec, pinned to a commit sha.
 *
 * The generated types are COMMITTED. That keeps `pnpm typecheck` working
 * offline, and makes a provider's breaking change visible as a diff in review
 * rather than only as a CI failure. `pnpm clients:check` regenerates and
 * fails when the working tree differs, which is the drift gate.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import { fetchSpecs, SPEC_SOURCES, type SpecService } from '../src/clients/spec_source.js';
import { ghFetcher } from '../src/clients/gh_fetcher.js';

const OUT_DIR = fileURLToPath(new URL('../src/clients/generated', import.meta.url));

const ref = process.env.SPEC_REF ?? 'develop';
const refs = Object.fromEntries(
  (Object.keys(SPEC_SOURCES) as SpecService[]).map((s) => [s, ref]),
) as Record<SpecService, string>;

const specs = await fetchSpecs(refs, ghFetcher);
await mkdir(OUT_DIR, { recursive: true });

const provenance: string[] = [];

for (const [service, spec] of Object.entries(specs) as [
  SpecService,
  { sha: string; body: string },
][]) {
  const ast = await openapiTS(JSON.parse(spec.body), { alphabetize: true });
  const header =
    `// GENERATED by scripts/generate_clients.ts — do not edit.\n` +
    `// ${SPEC_SOURCES[service].repo}@${spec.sha}:${SPEC_SOURCES[service].path}\n\n`;
  await writeFile(`${OUT_DIR}/${service}.ts`, header + astToString(ast));
  provenance.push(`${service} ${SPEC_SOURCES[service].repo}@${spec.sha}`);
  console.log(`generated ${service} from ${spec.sha.slice(0, 8)}`);
}

await writeFile(`${OUT_DIR}/PROVENANCE.txt`, provenance.sort().join('\n') + '\n');
console.log('done.');
